name: env
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - git
  - git-lfs
  - pip
  - pip:
    - transformers
    - sentencepiece
    - datasets
    - accelerate
    - deepspeed
    - protobuf==3.20
